### ISSUE TITLE
Bibtex file needs to have the same name as the LaTeX main file

### ISSUE THREAD

**Issue by phieber** [fracpete/latex-maven#11]
It is not obvious that the bibtex file needs to have the same name as the main latex file.
If the latex file is named sample.tex, the bibtex file needs to have sample.bib in order to have valid references. Maybe a good idea to make it clear in the very beginning ;)

**Comment by fracpete** [comment]
Suggestion for making it clearer?

**Comment by phieber** [comment]
Maybe a note in the README.md?

**Comment by fracpete** [comment]
Fork it, add it and make a pull request :-)

**Comment by phieber** [comment]
#12
