### ISSUE TITLE
Must be moved away from GitHub

### ISSUE THREAD

**Issue by mirabilos** [fracpete/latex-maven#8]
This project is under the Apache 2 licence with a NOTICE text file, effectively rendering an attribution requirement. As per http://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm such projects are no longer welcome on GitHub and legally **must** be moved elsewhere.

**Comment by fracpete** [comment]
See this discussion here:
http://groups.nzoss.org.nz/groups/openchat/messages/topic/2HUoxTbG9ZUzIYX8XRhkzd

**Comment by mirabilos** [comment]
“Each of the terms comes with an explanation as to why they need the rights,
along with notes to the effect of "only for this purpose",” is nice, but not enough.

For example, when I have a GPL’d work which is only GPL because I forked it off something GPL’d from the 1990s, I simply *cannot* upload it to GitHub any more as things are right now *because* I **legally cannot** waive the GPL requirements, no matter how much GitHub needs them or how only-for-this-purpose they are.

I’m in contact with them to get the ToS fixed. However, they unwisely chose to enact them yesterday, so, as things are right now, your project cannot legally be uploaded to GitHub any more (considering you aren’t the original author and can’t waive the NOTICE requirement).

**Comment by mirabilos** [comment]
The ToS got fixed, sorry for forgetting to close this issue.
